/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Entity;

import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Eugence
 */
public class GameLog extends javax.swing.JPanel {

    /**
     * Creates new form GameLog
     */
    
    public GameLog() {
        initComponents();
    }
    
    public void addNewMessage(String newMsg){
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String msg = sdf.format(new Date()) + " - " + newMsg + "\n";
        displayMessage(msg);
    }
    
    public void addSplitLine(){
        displayMessage("-----------------------------------------------------------\n");
    }
    
    public void displayMessage(String message){
        logBox.append(message);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        logBox = new javax.swing.JTextArea();
        title = new javax.swing.JLabel();

        scrollPane.setEnabled(false);

        logBox.setColumns(10);
        logBox.setForeground(new java.awt.Color(51, 51, 51));
        logBox.setLineWrap(true);
        logBox.setRows(35);
        logBox.setEnabled(false);
        scrollPane.setViewportView(logBox);

        title.setText("Game Log");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea logBox;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
